cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'common-fate/granted'
tap "azure/kubelogin"

brew 'gcc'
brew 'starship'
brew 'fzf'
brew 'kubernetes-cli'
brew 'krew'
brew 'istioctl'
brew 'eza'
brew 'tealdeer'
brew 'bat'
brew 'mcfly'
brew 'dog'
brew 'telnet'
brew 'granted'
brew 'awscli'
brew 'kubie'
brew 'Azure/kubelogin/kubelogin'
brew 'azure-cli'
brew 'terraform'
brew 'terraform-docs'
brew 'terragrunt'
brew 'jq'
brew 'kubent'
brew 'make'
brew 'vault'

cask 'webstorm'
cask 'visual-studio-code'
cask 'logitech-g-hub'
cask 'slack'
cask 'wezterm'
cask 'firefox'
cask 'google-cloud-sdk'
